### ISSUE TITLE
RDMA packet transmission

### ISSUE THREAD

**Issue by rbshi** [rbshi/coyote#1]
**Problem**
with both Vitis and Vivado HLS RDMA stack, the packet cannot be transmitted correctly. After several runs, the packages can be sent and received correctly (but the bpss_wr/rd_done signal is always zero).

**TODO** 
- [x] Check is sq is and rd/wr command is correct -- Yes: correct. 
- [x] Check the Tx/Rx package -- No: RDMA TX is correct, but total TX is not -- Maybe it's the MIE issue (hash table)?
- [x] Check the `axis_net` before and after MIE, check the `arp table req/reply` -- Normal😂  after one day, the RDMA WR works correctly.. Does the traffic interference this?? 
- [ ] #3

**Observation and Solutions**

> doArpLookUp needs time to take effect (delay after ip/mac change and lookup), see this picture, the lookup_reply is `0` at the beginning

![image](https://user-images.githubusercontent.com/25062575/179410437-cd22d153-199d-4832-8fb5-a638455f9a9c.png)

**Solutions:** add 1 second latency after doArpLookUp

**Comment by rbshi** [comment]
**Related issue in the driver**
The ipaddr in the arpLookUp is fixed to the `BASE_IP_ADDR` and `NODE_ID` in the driver.  Therefore the driver.h should be set for each machine. 

- [ ]  Get flexible arpLookUp ip address in the driver

**Comment by rbshi** [comment]
cb150bc2b7de56c15f626678bff56b98abe07727
